# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 02:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20170720_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='imgSrc',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(default='New Blog', max_length=150),
        ),
    ]
